/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Color,
} from './components/product-design/launch/color';

export namespace Components {
  interface AirbnbHomepage {}
  interface CardStack {
    /**
    * The collection of cards to render
    */
    'cards': any[];
  }
  interface CategoriesList {}
  interface CategoriesListItem {
    'icon': string;
    /**
    * The source to render as the background image.
    */
    'src': string;
  }
  interface IonAvatarGroup {
    /**
    * `true` if the avatar elements will animate apart.
    */
    'animated': boolean;
  }
  interface LaunchUiButton {
    'alignCenter': boolean;
    'alignLeft': boolean;
    'alignRight': boolean;
    /**
    * Displays the button at full-width.
    */
    'block': boolean;
    /**
    * Renders the button with a bold font weight.
    */
    'bold': boolean;
    /**
    * If the button is in a busy active state.
    */
    'busy': boolean;
    /**
    * The color display of the button.
    */
    'color': Color;
    /**
    * If the button is disabled and cannot be interacted with.
    */
    'disabled': boolean;
    /**
    * The filled color style for the button. `solid` renders the button with a solid background. `outline` renders the button only as a border. `clear` is a transparent button.
    */
    'fill': 'outline' | 'solid' | 'clear';
    /**
    * Renders the button large.
    */
    'lg': boolean;
    /**
    * Renders the button as a text link.
    */
    'link': boolean;
    /**
    * The rendered shape of the button. `rounded` has a small border radius, `square` has no border radius and `pill` has the maximum border radius.
    */
    'shape': 'rounded' | 'square' | 'pill' | 'circle';
    /**
    * Renders the button small.
    */
    'sm': boolean;
    /**
    * Softened color palette of the button.
    */
    'soft': boolean;
    /**
    * The type of button to render
    */
    'type': 'submit' | 'button' | 'reset';
    /**
    * Renders the button extra large.
    */
    'xl': boolean;
  }
  interface ProgressRing {
    /**
    * The foreground color of the ring as it fills.
    */
    'circleClass': string;
    /**
    * The progress percentage to whole for the progress ring.
    */
    'progress': number;
    /**
    * The radius of the ring in pixels.
    */
    'radius': number;
    /**
    * The stroke width of the progress ring.
    */
    'stroke': number;
  }
}

declare global {


  interface HTMLAirbnbHomepageElement extends Components.AirbnbHomepage, HTMLStencilElement {}
  var HTMLAirbnbHomepageElement: {
    prototype: HTMLAirbnbHomepageElement;
    new (): HTMLAirbnbHomepageElement;
  };

  interface HTMLCardStackElement extends Components.CardStack, HTMLStencilElement {}
  var HTMLCardStackElement: {
    prototype: HTMLCardStackElement;
    new (): HTMLCardStackElement;
  };

  interface HTMLCategoriesListElement extends Components.CategoriesList, HTMLStencilElement {}
  var HTMLCategoriesListElement: {
    prototype: HTMLCategoriesListElement;
    new (): HTMLCategoriesListElement;
  };

  interface HTMLCategoriesListItemElement extends Components.CategoriesListItem, HTMLStencilElement {}
  var HTMLCategoriesListItemElement: {
    prototype: HTMLCategoriesListItemElement;
    new (): HTMLCategoriesListItemElement;
  };

  interface HTMLIonAvatarGroupElement extends Components.IonAvatarGroup, HTMLStencilElement {}
  var HTMLIonAvatarGroupElement: {
    prototype: HTMLIonAvatarGroupElement;
    new (): HTMLIonAvatarGroupElement;
  };

  interface HTMLLaunchUiButtonElement extends Components.LaunchUiButton, HTMLStencilElement {}
  var HTMLLaunchUiButtonElement: {
    prototype: HTMLLaunchUiButtonElement;
    new (): HTMLLaunchUiButtonElement;
  };

  interface HTMLProgressRingElement extends Components.ProgressRing, HTMLStencilElement {}
  var HTMLProgressRingElement: {
    prototype: HTMLProgressRingElement;
    new (): HTMLProgressRingElement;
  };
  interface HTMLElementTagNameMap {
    'airbnb-homepage': HTMLAirbnbHomepageElement;
    'card-stack': HTMLCardStackElement;
    'categories-list': HTMLCategoriesListElement;
    'categories-list-item': HTMLCategoriesListItemElement;
    'ion-avatar-group': HTMLIonAvatarGroupElement;
    'launch-ui-button': HTMLLaunchUiButtonElement;
    'progress-ring': HTMLProgressRingElement;
  }
}

declare namespace LocalJSX {
  interface AirbnbHomepage {}
  interface CardStack {
    /**
    * The collection of cards to render
    */
    'cards'?: any[];
  }
  interface CategoriesList {}
  interface CategoriesListItem {
    'icon'?: string;
    /**
    * The source to render as the background image.
    */
    'src'?: string;
  }
  interface IonAvatarGroup {
    /**
    * `true` if the avatar elements will animate apart.
    */
    'animated'?: boolean;
  }
  interface LaunchUiButton {
    'alignCenter'?: boolean;
    'alignLeft'?: boolean;
    'alignRight'?: boolean;
    /**
    * Displays the button at full-width.
    */
    'block'?: boolean;
    /**
    * Renders the button with a bold font weight.
    */
    'bold'?: boolean;
    /**
    * If the button is in a busy active state.
    */
    'busy'?: boolean;
    /**
    * The color display of the button.
    */
    'color'?: Color;
    /**
    * If the button is disabled and cannot be interacted with.
    */
    'disabled'?: boolean;
    /**
    * The filled color style for the button. `solid` renders the button with a solid background. `outline` renders the button only as a border. `clear` is a transparent button.
    */
    'fill'?: 'outline' | 'solid' | 'clear';
    /**
    * Renders the button large.
    */
    'lg'?: boolean;
    /**
    * Renders the button as a text link.
    */
    'link'?: boolean;
    /**
    * Event emitted each time the button is clicked
    */
    'onTap'?: (event: CustomEvent<any>) => void;
    /**
    * The rendered shape of the button. `rounded` has a small border radius, `square` has no border radius and `pill` has the maximum border radius.
    */
    'shape'?: 'rounded' | 'square' | 'pill' | 'circle';
    /**
    * Renders the button small.
    */
    'sm'?: boolean;
    /**
    * Softened color palette of the button.
    */
    'soft'?: boolean;
    /**
    * The type of button to render
    */
    'type'?: 'submit' | 'button' | 'reset';
    /**
    * Renders the button extra large.
    */
    'xl'?: boolean;
  }
  interface ProgressRing {
    /**
    * The foreground color of the ring as it fills.
    */
    'circleClass'?: string;
    /**
    * The progress percentage to whole for the progress ring.
    */
    'progress'?: number;
    /**
    * The radius of the ring in pixels.
    */
    'radius'?: number;
    /**
    * The stroke width of the progress ring.
    */
    'stroke'?: number;
  }

  interface IntrinsicElements {
    'airbnb-homepage': AirbnbHomepage;
    'card-stack': CardStack;
    'categories-list': CategoriesList;
    'categories-list-item': CategoriesListItem;
    'ion-avatar-group': IonAvatarGroup;
    'launch-ui-button': LaunchUiButton;
    'progress-ring': ProgressRing;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'airbnb-homepage': LocalJSX.AirbnbHomepage & JSXBase.HTMLAttributes<HTMLAirbnbHomepageElement>;
      'card-stack': LocalJSX.CardStack & JSXBase.HTMLAttributes<HTMLCardStackElement>;
      'categories-list': LocalJSX.CategoriesList & JSXBase.HTMLAttributes<HTMLCategoriesListElement>;
      'categories-list-item': LocalJSX.CategoriesListItem & JSXBase.HTMLAttributes<HTMLCategoriesListItemElement>;
      'ion-avatar-group': LocalJSX.IonAvatarGroup & JSXBase.HTMLAttributes<HTMLIonAvatarGroupElement>;
      'launch-ui-button': LocalJSX.LaunchUiButton & JSXBase.HTMLAttributes<HTMLLaunchUiButtonElement>;
      'progress-ring': LocalJSX.ProgressRing & JSXBase.HTMLAttributes<HTMLProgressRingElement>;
    }
  }
}


